@port = 3000
@baseURL = http://localhost:{{port}}
@basePostsURL = {{baseURL}}/post
@postId = 694582383d983573299dc89b
@senderId = 6945824e5cb700d554aa53a0

### Add a New Post
POST {{basePostsURL}}
content-type: application/json

{
  "senderId": "<sender_id>",
  "title": "Title 1",
  "content": "Content 1"
}

# EXAMPLE
# {
#   "senderId": "{{senderId}}",
#   "title": "Title 1",
#   "content": "Content 1"
# }

### Get All Posts
GET {{basePostsURL}}


### Get a Post by ID (EXAMPLE)
GET {{basePostsURL}}/{{postId}}

### Get a Post by ID
GET {{basePostsURL}}/<post_id>

### Get Posts by Sender (EXAMPLE)
GET {{basePostsURL}}/?sender={{senderId}}

### Get Posts by Sender
GET {{basePostsURL}}/?sender=<sender_id>

### Delete All Posts
DELETE  {{basePostsURL}}

### Delete Post by ID (EXAMPLE)
DELETE  {{basePostsURL}}/{{postId}}

### Delete Post by ID
DELETE  {{basePostsURL}}/<post_id>
