@port = 3000
@baseURL = http://localhost:{{port}}
@basePostsURL = {{baseURL}}/post
@postId = 694582383d983573299dc89b
@senderId = 6945824e5cb700d554aa53a0

### Add a New Post
POST {{basePostsURL}}
content-type: application/json

{
  "senderId": "{{senderId}}",
  "title": "Title 1",
  "content": "Content 1"
}

### Get All Posts
GET {{basePostsURL}}

### Get a Post by ID
GET {{basePostsURL}}/{{postId}}

### Get Posts by Sender
GET {{basePostsURL}}/?sender={{senderId}}

// TODO: DELETE all POSTS
// TODO: DELETE POST by id
